In [4]:
# Import the Pandas library
import pandas as pd

# Import SQL Alchemy
from sqlalchemy import create_engine

In [5]:
# Create a reference the CSV file desired
csv_path = "netflix_movies_tvshows.csv"

# Read the CSV into a Pandas DataFrame
Netflix_df = pd.read_csv(csv_path)

# Print the dataframe
Netflix_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
# Create Database Connection
engine = create_engine("sqlite:///Netflix_moviesandTvshows.sqlite")

#Export table as sqlite database
Netflix_df.to_sql("netflix", engine, if_exists="replace", index=False)

OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL:
DROP TABLE netflix]
(Background on this error at: http://sqlalche.me/e/e3q8)

In [15]:
df=pd.read_sql("select * from netflix",engine)
df
year="2020,2021"
type= "TV Show"
grouped= df[(df["release_year"].isin(map(int,year.split(','))))&(df["type"].isin(type.split(',')))].groupby(["director","type"]).count().sort_values("title",ascending=False)["title"].reset_index()
grouped[0:10]

                                            director     type  title
0                          Adrien Lagier, Ousmane Ly  TV Show      1
1                                   Pavel Kostomarov  TV Show      1
2                                        Oriol Paulo  TV Show      1
3                                    Olivier Megaton  TV Show      1
4  Norm Hiscock, Gary Howsam, Mike Smith, John Pa...  TV Show      1
5                            Nopparoj Chotmunkongsit  TV Show      1
6  Moyoung Jin, Caroline Sá, Deepti Kakkar, Fahad...  TV Show      1
7                                      Mike Flanagan  TV Show      1
8                     Mauricio Dias, Tatiana Villela  TV Show      1
9                                          Mateo Gil  TV Show      1

In [20]:
# Create a reference the CSV file desired
csv_path = "netflix_movies_tvshows.csv"

# Read the CSV into a Pandas DataFrame
Netflix_df = pd.read_csv(csv_path)

Netflix_df.to_html("templates/dataexport.html")